In [2]:
import psycopg2
import pandas as pd
from pandas.plotting import register_matplotlib_converters 

# Connect to covid19db.org
conn = psycopg2.connect(
    host='covid19db.org',
    port=5432,
    dbname='covid19',
    user='covid19',
    password='covid19'
)
cur = conn.cursor()
cur.execute("""SELECT m.* FROM mobility AS m 
WHERE country='Poland' AND 
adm_area_1 IS NULL AND
adm_area_2 IS NULL
ORDER BY date
""")

mobility_data = pd.DataFrame(cur.fetchall(), columns=[desc[0] for desc in cur.description])
mobility_data.head()

,source,date,country,countrycode,adm_area_1,adm_area_2,adm_area_3,transit_stations,residential,workplace,parks,retail_recreation,grocery_pharmacy
0,GOOGLE_MOBILITY,2020-02-23,Poland,POL,None,None,None,-2.429,1.589,-3.972,-37.063,-8.609,-31.432
1,GOOGLE_MOBILITY,2020-02-24,Poland,POL,None,None,None,3.215,-0.867,10.482,-4.840,1.273,0.835
2,GOOGLE_MOBILITY,2020-02-25,Poland,POL,None,None,None,5.822,0.084,10.609,6.187,0.857,2.213
3,GOOGLE_MOBILITY,2020-02-26,Poland,POL,None,None,None,4.306,-0.469,10.153,4.006,-2.270,-2.608
4,GOOGLE_MOBILITY,2020-02-27,Poland,POL,None,None,None,6.584,-0.554,10.229,4.989,4.369,4.519